### PR TITLE
Fix default.nix

### PR DESCRIPTION
**Pull request by jakobrs**
**Edit:** Ready to be merged

Should fix regression caused by commit 1247f3a. There are still 843 errors when running `nix-shell`, but those were there before 1247f3a as well.

Note that the build instructions on <https://everestapi.github.io> appear to be wrong (as of commit 7312341):
```bash
nix-env -f default.nix -iA everest
```
should be one of
```bash
nix-env -f default.nix -i  # Remove --attr everest
nix-env -f . -i            # Equivalent
nix-build                  # Doesn't permanently install anything
nix-shell                  # Same as nix-build, but also launches a shell with
                           # miniinstaller available
```

### CODE REVIEW

**Comment by jakobrs** [comment]
Everest now compiles; I'll test it and then push.

**Comment by jakobrs** [comment]
Everest now seems to work, although the installer crashes when run twice (due to permissions). It's also very volatile: I recommend `cd`ing into the installation folder and running `miniinstaller .` there. It also shows the wrong version number in-game.

Tested on macOS using `Speedrun Tool` by DemoJameson.

**Comment by jakobrs** [comment]
That should have been the last change. This should now be ready to be merged

**Comment by jakobrs** [comment]
Let’s hope that was all

**Comment by 0x0ade** [comment]
image

Just tell me when I can merge this and hope that it never breaks ever again.

**Comment by jakobrs** [comment]
Sorry for force pushing earlier.

I've tested it on macOS and Linux (on Epic Games and Steam), and it seems to work now.

**Comment by jakobrs** [comment]
Just to be clear, I'm "fairly" sure this can now be merged.

**Comment by jakobrs** [comment]
This should now be ready to be merged. Sorry for force-pushing again.

**Pull request merged**
