### PR TITLE
Fix TrailManager confusion when sprite are large or player hair is too long

### PR DESCRIPTION
**Pull request by AAA1459**
fix: 
7KMB{$SB6OGDW9OT($ Y88S

### CODE REVIEW

**Comment by maddie480** [comment]
looks like there's a lot of `MonoModReplace` 🤔 how much of it is vanilla copypaste?

**Comment by AAA1459** [comment]
Almost all, except `buffers` related

**Comment by AAA1459** [comment]
Don't merge this now, wait me a sec

**Comment by maddie480** [comment]
I'm wondering if you could make an IL patch instead, to avoid replacing code as much as possible 🤔

**Comment by AAA1459** [comment]
> I'm wondering if you could make an IL patch instead, to avoid replacing code as much as possible 🤔

I am not familiar with IL only know how to emit a delegate. but i probably could, except `BeforeRender` that almost is rewritten

**Comment by AAA1459** [comment]
@maddie480 oh thanks you, that gave me a very good reference.

**Pull request merged**
