### PR TITLE
Expose more elements of KeyboardConfigUI

### PR DESCRIPTION
**Pull request by PenguinOwl**
This patch makes adding new keyboard config screens much easier.
There might be a dead variable or two from the orig class, but most of
it should be good.

### CODE REVIEW

**Comment by max4805** [comment]
image

This changes the labels in the vanilla key binding menu.

**Comment by max4805** [comment]
[I'm currently working on that, just to add comments and such.]

**Comment by max4805** [comment]
When I wrote the docs for `GetRemapList` I noticed it was quite weird... since it did the remapping for keys that do not support multiple bindings (directional keys in vanilla), but just returned the list of _existing_ bindings for keys that support multiple bindings.

So I replaced this with a `RemapKey` method that does the remapping itself.

Also fixed the labels in the vanilla key binding menu by making the `GetLabel` default implementation call the vanilla `Label` method.

**Comment by max4805** [comment]
I'm... pretty much done with my vacuum cleaning job here. Leaving that for review now!

**Comment by PenguinOwl** [comment]
Thanks max for the clean-up!

One thing, I am actually still in favor of using `GetRemapList` over having modders remap the keys by themselves. It takes out a lot of the bloat in the custom class, as they only have to return the field in their settings file. It also saves them from implementing having to implement additive keys. For example,
```cs
protected override List<Keys> GetRemapList(int remapping, Keys newKey)
{
    Mappings mapping = (Mappings)remapping;
    if (mapping == Mappings.SpawnJelly)
    {
        return LiquidMod.Settings.SpawnJelly;
    }
    return null;
}
```
An easy way to document it would be
```
// Return the list to remap with. This should be a field in your settings class. To prevent the remap from happening, return null.
```

**Comment by max4805** [comment]
Agreed for `GetRemapList`: even if the vanilla implementation is weird (and also _sets_ key bindings), this makes sense for modders implementing it and spares them ~5 lines of code they would have to write all the time to actually update the bindings.

Plus, I made `SupportsMultipleBindings` that is supposed to be overriden... private. Good job Max. :sweat:

**Comment by max4805** [comment]
Looks good to me now. Thanks for fixing my fix 😅

**Pull request merged**
