### PR TITLE
Change RainbowMod's name to Fabeline

### PR DESCRIPTION
**Pull request by leo60228**
I don't entirely see what mod name localization support has to do with this.

### CODE REVIEW

**Comment by 0x0ade** [comment]
_Oh,_ I thought you meant the mod options menu title. That's in the RainbowMod English.txt. Do you also want to change that?

**Comment by leo60228** [comment]
I built it and it changed the mod options menu title... :thinking:

**Comment by 0x0ade** [comment]
Because it defaults to that when no other name is given. It'd be best to just set the mod options menu title in English.txt, unless you also want to change the settings and cached .dll path.

**Comment by 0x0ade** [comment]
I just pushed https://github.com/EverestAPI/Everest/commit/6d201abba4ca09d43a28e9f966dab6b835f08635 to master, which updates English.txt accordingly.

Do we still want to change the config and cached .dll paths by changing the mod name?

**Pull request closed without merging**
