### PR TITLE
Integrate Update Checker into Everest

### PR DESCRIPTION
**Pull request by max4805**
This aims to integrate https://gamebanana.com/gamefiles/9920 into Everest directly.

The part I'm the most unsure of here is the method extraction in `Everest.Updater`. The code used by the code mod is pretty much the same as Everest's own updater to download the package while keeping track of progress, so I tried extracting it into a method.

**Not ready to be merged yet**, as if you open a save file, close it, then install updates, Celeste will reboot into the save file directly, which isn't really what should happen.

### CODE REVIEW

**Comment by max4805** [comment]
Opening a save file, then exiting it and pressing Ctrl+F5 also makes the game automatically reload the save.

**Comment by max4805** [comment]
Any advice about how to fix that oddity? This is caused by the fact that even when you exit a save file, `SaveData.Instance` still keeps its value. One way I found to "solve" this is to set it to `null` in `OuiMainMenu.Enter` (since this is always where you get by exiting a save file), but that sounds terrible. Checking in `QuickFullRestart` if we actually are in a save file also sounds painful 🤔

**Comment by 0x0ade** [comment]
That oddity is taken care of now :)

**Comment by max4805** [comment]
Cool, thanks :) The update checker should always restart to the title screen now.

**Pull request merged**
